# Copyright 2014-2016 Spotify AB
# Copyright 2016-2018 The Last Pickle Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
sudo: required
language: java
dist: xenial
addons:
  postgresql: '9.4'
jdk:
- openjdk8
branches:
  only:
  - "/^strapdata.*$/"
env:
  global:
  - LOCAL_JMX=no
  - TEST=""
stages:
- Integration Tests
- Distributed Reaper Integration Tests
- Flapping Distributed Reaper Integration Tests
- name: Upgrade Integration Tests
- Docker
- name: Deploy
  if: branch = strapdata-1.4.6 OR tag IS present
jobs:
  fast_finish: true
  allow_failures:
  - env: TEST_TYPE=docker
  - env: TEST_TYPE=ccm CASSANDRA_VERSION=git:trunk GRIM_MIN=1 GRIM_MAX=1
  - env: TEST_TYPE=ccm CASSANDRA_VERSION=git:trunk GRIM_MIN=2 GRIM_MAX=2
  - env: TEST_TYPE=ccm CASSANDRA_VERSION=git:trunk GRIM_MIN=2 GRIM_MAX=4
  - env: TEST_TYPE=upgrade CASSANDRA_VERSION=git:trunk CO="-t @all_nodes_reachable"
  - env: TEST_TYPE=upgrade CASSANDRA_VERSION=git:trunk CO="-t ~@all_nodes_reachable"
  include:
  - stage: Integration Tests
    name: Memory, H2 and Postgresql
    env: TEST_TYPE=ccm CASSANDRA_VERSION=2.1.20
  - stage: Integration Tests
    name: Cassandra 3.11.3
    env: TEST_TYPE=ccm CASSANDRA_VERSION=3.11.3 GRIM_MIN=1 GRIM_MAX=1
  - stage: Integration Tests
    name: Cassandra 4.0
    env: TEST_TYPE=ccm CASSANDRA_VERSION=git:trunk GRIM_MIN=1 GRIM_MAX=1
  - stage: Distributed Reaper Integration Tests
    name: Two Reapers on Cassandra 3.11.3
    env: TEST_TYPE=ccm CASSANDRA_VERSION=3.11.3 GRIM_MIN=2 GRIM_MAX=2
  - stage: Distributed Reaper Integration Tests
    name: Two Reapers on Cassandra 4.0
    env: TEST_TYPE=ccm CASSANDRA_VERSION=git:trunk GRIM_MIN=2 GRIM_MAX=2
  - stage: Flapping Distributed Reaper Integration Tests
    name: Four Flapping Reaper on Cassandra 3.11.3
    env: TEST_TYPE=ccm CASSANDRA_VERSION=3.11.3 GRIM_MIN=2 GRIM_MAX=4
  - stage: Flapping Distributed Reaper Integration Tests
    name: Four Flapping Reaper on Cassandra 4.0
    env: TEST_TYPE=ccm CASSANDRA_VERSION=git:trunk GRIM_MIN=2 GRIM_MAX=4
  - stage: Upgrade Integration Tests
    name: Upgrading Reaper on Cassandra 3.11.3 (all_nodes_reachable)
    env: TEST_TYPE=upgrade CASSANDRA_VERSION=3.11.3 CO="-t @all_nodes_reachable"
  - stage: Upgrade Integration Tests
    name: Upgrading Reaper on Cassandra 3.11.3
    env: TEST_TYPE=upgrade CASSANDRA_VERSION=3.11.3 CO="-t ~@all_nodes_reachable"
  - stage: Upgrade Integration Tests
    name: Upgrading Reaper on Cassandra 4.0 (all_nodes_reachable)
    env: TEST_TYPE=upgrade CASSANDRA_VERSION=git:trunk CO="-t @all_nodes_reachable"
  - stage: Upgrade Integration Tests
    name: Upgrading Reaper on Cassandra 4.0
    env: TEST_TYPE=upgrade CASSANDRA_VERSION=git:trunk CO="-t ~@all_nodes_reachable"
  - stage: Deploy
    name: Deploy
    env: TEST_TYPE=deploy
    before_deploy: "./src/ci/before_deploy.sh"
    deploy:
    - provider: releases
      api_key:
        secure: MFhecFMYXJRTZYYTY0zrvQyDoTUXtaODNuF/Im7pFZDbC7aWgo5s8HFmyzNpJADKwydO1RLFPpEhJGTJ/FbuTDvshc/PirzVbrVr4jK0hnNCFaYEBqOypJzoR1j5bdivmMWxaHVvKEfAr+iNs9fwEVeb3uS+JrsZspImBkDbbeuOq0SKyxl1CrE1KF3aZJWOv50zKJaGyre9dKUq9JL8Js2dNKpebYhP8tjhD7iShD344I00br9qu3ThZ3rG6LTv4c3llI0ZRhWb644iNFtz9CoKQXK30ATjh1avT1wZr6Ci+62kYAePBToagbHd5xs8S78hFkUcm7Z0/8XX8m5KJNyJl+MSh0F/vkEpBJaLSqwUPcgbEB5wqYvWDTWADY9rQ80Mv6I97kmxpYPGpRLONBxjDby2fUVGnyr+7tWhAmAXOomtMXMl6LOLHCp0gNFMO2Twp77vTRz8e38B2dJ5vg155bGNHM7kBwP3EuiKiKFwA+RUpukVLQon7foGvikEsB1HLrNoOg44QEzrcEL6UP9tHyEFWWfwSnD3q7ybQ7bjzFC4N9F1t/NpYI2icR8X/3dRrj4GjWMCMWK75HZWjycrfd0nNLdhKyGAw2rlTmgq6Sypm3g80aq3LvGJ+Pnb7s6B2IAzNgOyhT8TKlIILZ3wQlYMrVBaVaMTmRItHWY=
      file_glob: true
      file:
      - src/packages/cassandra-reaper-${TRAVIS_TAG}-release.tar.gz
      - src/packages/reaper-*-1.x86_64.rpm
      - src/packages/reaper_*_amd64.deb
      skip_cleanup: true
      on:
        tags: true
    - provider: script
      script:
        - mvn -pl src/server/ docker:build  -Ddocker.directory=src/server/src/main/docker
        - docker tag cassandra-reaper:latest docker.repo.strapdata.com/strapdata/cassandra-reaper:latest
        - docker push docker.repo.strapdata.com/strapdata/cassandra-reaper:latest
        #- docker tag cassandra-reaper:latest strapdata.azurecr.io/strapdata/cassandra-reaper:${TARVIS_TAG}
        #- docker tag cassandra-reaper:latest gcr.io/strapdata-factory/cassandra-reaper:${TARVIS_TAG}
      skip_cleanup: true
      on:
        tags: false
        branch: strapdata-1.4.6
services:
- postgresql
- docker
before_install:
  - echo "$NEXUS_USERNAME"
  - echo "$NEXUS_PASSWORD" | docker login --username "$NEXUS_USERNAME" docker.repo.strapdata.com --password-stdin
  - "./src/ci/before_install.sh"
install: "./src/ci/install.sh"
before_script: "./src/ci/before_script.sh"
script: "./src/ci/script.sh"
after_failure: "./src/ci/after_failure.sh"
