sudo: required
language: java
dist: xenial
addons:
  postgresql: '9.4'
jdk:
  - openjdk8
branches:
  only:
  - "/^strapdata.*$/"
env:
  global:
  - LOCAL_JMX=no
  - TEST=""
  - secure: V9i472cZD/xrx1g2mpsbDJZx7WVJU3HXjo/kqdV1xCL0omSRNkksDjimCE8zAKUo7bfzj6jSoQIhQ8MpmQfoGRUmCkBlx9W6+1t19AerhYrD/ZcVq12SWtzn1aCPo2G0AniqNOZ6ON8N/aTMxXbkpYwJkqtqWqqn4MrGIo+NGYKnCL+39d44WyF0jLpbycE5nj3jRAL4J2+4Ate4VcSLHv9ABW0SEgY2lZ7YVHrO+PrIfOHmYHs3yMYGq95o8HsreZcVsdfDSAccMtrx3EZ/RFeF5//EoQzcH3uo7mkHCl3bCalnrbJ9j6A2dCpYiIe0VSrovDyS9Rg3QQjUqhT2Gn3iA4Y12qZuPSjXf9LgKbCMcFnqi7UjDeZ4LQEyEiBy/OLqRYnksCQ6/j1MnLG3whNNdC2Gy98mXgD9IO1RCnz3vNfrCu3djelj2T3PnVmJ23bmdcSM2VsMqi3W7SOvMNjWPfTWF1uK8yvw+AYZgi8pUjNRuwxrM7pkNXTSdtlqIFMV5D8ZO4sc4cKAnxKpaYs6qRX8gI3biH4W7C7537I1kR244EyEv8g55HE750UJIqkJTAQ9Yv1npwyo1kGPWVy5ppVqkk4LPmHOslhmK9rJiMeAXWsqQ4VCdZ+nDI29wNFNTnNd8RHUIk2fOyXudKdApi5yJ7t7LtdSKqaHZKg=
  - secure: Hxg9XAvk7z7GHlymSvFYINqztzcKtvRhCuaTBq+z25P68Y6tNUUoWNkdRgA0KadyLcxNkt/+g+kxVOKTqyv8rQcBj4xu7oqWgr5byZC1xx6quNoWsz3S7/NEXkpJRWsSYIeevb9RXoaFH7N7lJUywASs3TPmvp772VT6n7Tpg45924wvgnJduRxGAvk87h/McjUAnsrrskoBsVFpxw7hjZ3ooldg+/8rHC4M644jcXpIUtFJFhGgS/zNyzhk8oZZE/N7i0MLftMiXV4WSKbwE9RESjO2YePCawFJPpuBELqmTW85wq27bb2AS5BPSByalaefkh7XthcyxNv7MJ+n4RaOhTYekSES9vsm7/zzcw02EyiufeuAB4on5BbL4VYdgwN7/7JuWqshcoj//YwjDolB/fjGgZ65jVaTQunoA6Clsgihk4vsxLGCC5RS/dg7AyS+XXmz6wGb3VKgzMiWr5juJD3XxAlrmMgrC102z2GyJxjjjIieM/rjV7qLqYsVyEbK2wncRG7NTZ69E9XKhw29SSyJZNToYlgJN3MjQVypWET8sSxQvAPomC5yKbpZ9Ippei42xr/0tvndAg5Ao3Wi1WYryYCEFdJpBojbURAYlCY1HBbSbKUbRwFq/nsVoxOJotP8PpidK+1XGbTqB79lkVJ6DIojlyoAafavb9I=
stages:
- Integration Tests
- Distributed Reaper Integration Tests
- Flapping Distributed Reaper Integration Tests
- name: Upgrade Integration Tests
- Docker
- name: Deploy
  if: branch = strapdata-1.4.6 OR tag IS present
jobs:
  fast_finish: true
  allow_failures:
  - env: TEST_TYPE=docker
  - env: TEST_TYPE=ccm CASSANDRA_VERSION=git:trunk GRIM_MIN=1 GRIM_MAX=1
  - env: TEST_TYPE=ccm CASSANDRA_VERSION=git:trunk GRIM_MIN=2 GRIM_MAX=2
  - env: TEST_TYPE=ccm CASSANDRA_VERSION=git:trunk GRIM_MIN=2 GRIM_MAX=4
  - env: TEST_TYPE=upgrade CASSANDRA_VERSION=git:trunk CO="-t @all_nodes_reachable"
  - env: TEST_TYPE=upgrade CASSANDRA_VERSION=git:trunk CO="-t ~@all_nodes_reachable"
  include:
  - stage: Integration Tests
    name: Memory, H2 and Postgresql
    env: TEST_TYPE=ccm CASSANDRA_VERSION=2.1.20
  - stage: Integration Tests
    name: Cassandra 2.1.20
    env: TEST_TYPE=ccm CASSANDRA_VERSION=2.1.20 GRIM_MIN=1 GRIM_MAX=1
  - stage: Integration Tests
    name: Cassandra 2.2.13
    env: TEST_TYPE=ccm CASSANDRA_VERSION=2.2.13 GRIM_MIN=1 GRIM_MAX=1
  - stage: Integration Tests
    name: Cassandra 3.0.17
    env: TEST_TYPE=ccm CASSANDRA_VERSION=3.0.17 GRIM_MIN=1 GRIM_MAX=1
  - stage: Integration Tests
    name: Cassandra 3.11.3
    env: TEST_TYPE=ccm CASSANDRA_VERSION=3.11.3 GRIM_MIN=1 GRIM_MAX=1
  - stage: Integration Tests
    name: Cassandra 4.0
    env: TEST_TYPE=ccm CASSANDRA_VERSION=git:trunk GRIM_MIN=1 GRIM_MAX=1
  - stage: Distributed Reaper Integration Tests
    name: Two Reapers on  Cassandra 2.1.20
    env: TEST_TYPE=ccm CASSANDRA_VERSION=2.1.20 GRIM_MIN=2 GRIM_MAX=2
  - stage: Distributed Reaper Integration Tests
    name: Two Reapers on Cassandra 2.2.13
    env: TEST_TYPE=ccm CASSANDRA_VERSION=2.2.13 GRIM_MIN=2 GRIM_MAX=2
  - stage: Distributed Reaper Integration Tests
    name: Two Reapers on Cassandra 3.0.17
    env: TEST_TYPE=ccm CASSANDRA_VERSION=3.0.17 GRIM_MIN=2 GRIM_MAX=2
  - stage: Distributed Reaper Integration Tests
    name: Two Reapers on Cassandra 3.11.3
    env: TEST_TYPE=ccm CASSANDRA_VERSION=3.11.3 GRIM_MIN=2 GRIM_MAX=2
  - stage: Distributed Reaper Integration Tests
    name: Two Reapers on Cassandra 4.0
    env: TEST_TYPE=ccm CASSANDRA_VERSION=git:trunk GRIM_MIN=2 GRIM_MAX=2
  - stage: Flapping Distributed Reaper Integration Tests
    name: Four Flapping Reaper on Cassandra 2.1.20
    env: TEST_TYPE=ccm CASSANDRA_VERSION=2.1.20 GRIM_MIN=2 GRIM_MAX=4
  - stage: Flapping Distributed Reaper Integration Tests
    name: Four Flapping Reaper on Cassandra 2.2.13
    env: TEST_TYPE=ccm CASSANDRA_VERSION=2.2.13 GRIM_MIN=2 GRIM_MAX=4
  - stage: Flapping Distributed Reaper Integration Tests
    name: Four Flapping Reaper on Cassandra 3.0.17
    env: TEST_TYPE=ccm CASSANDRA_VERSION=3.0.17 GRIM_MIN=2 GRIM_MAX=4
  - stage: Flapping Distributed Reaper Integration Tests
    name: Four Flapping Reaper on Cassandra 3.11.3
    env: TEST_TYPE=ccm CASSANDRA_VERSION=3.11.3 GRIM_MIN=2 GRIM_MAX=4
  - stage: Flapping Distributed Reaper Integration Tests
    name: Four Flapping Reaper on Cassandra 4.0
    env: TEST_TYPE=ccm CASSANDRA_VERSION=git:trunk GRIM_MIN=2 GRIM_MAX=4
  - stage: Upgrade Integration Tests
    name: Upgrading Reaper on Cassandra 2.1.20 (all_nodes_reachable)
    env: TEST_TYPE=upgrade CASSANDRA_VERSION=2.1.20 CO="-t @all_nodes_reachable"
  - stage: Upgrade Integration Tests
    name: Upgrading Reaper on Cassandra 2.1.20
    env: TEST_TYPE=upgrade CASSANDRA_VERSION=2.1.20 CO="-t ~@all_nodes_reachable"
  - stage: Upgrade Integration Tests
    name: Upgrading Reaper on Cassandra 2.2.13 (all_nodes_reachable)
    env: TEST_TYPE=upgrade CASSANDRA_VERSION=2.2.13 CO="-t @all_nodes_reachable"
  - stage: Upgrade Integration Tests
    name: Upgrading Reaper on Cassandra 2.2.13
    env: TEST_TYPE=upgrade CASSANDRA_VERSION=2.2.13 CO="-t ~@all_nodes_reachable"
  - stage: Upgrade Integration Tests
    name: Upgrading Reaper on Cassandra 3.0.17 (all_nodes_reachable)
    env: TEST_TYPE=upgrade CASSANDRA_VERSION=3.0.17 CO="-t @all_nodes_reachable"
  - stage: Upgrade Integration Tests
    name: Upgrading Reaper on Cassandra 3.0.17
    env: TEST_TYPE=upgrade CASSANDRA_VERSION=3.0.17 CO="-t ~@all_nodes_reachable"
  - stage: Upgrade Integration Tests
    name: Upgrading Reaper on Cassandra 3.11.3 (all_nodes_reachable)
    env: TEST_TYPE=upgrade CASSANDRA_VERSION=3.11.3 CO="-t @all_nodes_reachable"
  - stage: Upgrade Integration Tests
    name: Upgrading Reaper on Cassandra 3.11.3
    env: TEST_TYPE=upgrade CASSANDRA_VERSION=3.11.3 CO="-t ~@all_nodes_reachable"
  - stage: Upgrade Integration Tests
    name: Upgrading Reaper on Cassandra 4.0 (all_nodes_reachable)
    env: TEST_TYPE=upgrade CASSANDRA_VERSION=git:trunk CO="-t @all_nodes_reachable"
  - stage: Upgrade Integration Tests
    name: Upgrading Reaper on Cassandra 4.0
    env: TEST_TYPE=upgrade CASSANDRA_VERSION=git:trunk CO="-t ~@all_nodes_reachable"
  - stage: Docker
    env: TEST_TYPE=docker
  - stage: Deploy
    name: Deploy
    env: TEST_TYPE=deploy
    before_deploy: "./src/ci/before_deploy.sh"
    deploy:
    - provider: releases
      api_key:
        secure: MFhecFMYXJRTZYYTY0zrvQyDoTUXtaODNuF/Im7pFZDbC7aWgo5s8HFmyzNpJADKwydO1RLFPpEhJGTJ/FbuTDvshc/PirzVbrVr4jK0hnNCFaYEBqOypJzoR1j5bdivmMWxaHVvKEfAr+iNs9fwEVeb3uS+JrsZspImBkDbbeuOq0SKyxl1CrE1KF3aZJWOv50zKJaGyre9dKUq9JL8Js2dNKpebYhP8tjhD7iShD344I00br9qu3ThZ3rG6LTv4c3llI0ZRhWb644iNFtz9CoKQXK30ATjh1avT1wZr6Ci+62kYAePBToagbHd5xs8S78hFkUcm7Z0/8XX8m5KJNyJl+MSh0F/vkEpBJaLSqwUPcgbEB5wqYvWDTWADY9rQ80Mv6I97kmxpYPGpRLONBxjDby2fUVGnyr+7tWhAmAXOomtMXMl6LOLHCp0gNFMO2Twp77vTRz8e38B2dJ5vg155bGNHM7kBwP3EuiKiKFwA+RUpukVLQon7foGvikEsB1HLrNoOg44QEzrcEL6UP9tHyEFWWfwSnD3q7ybQ7bjzFC4N9F1t/NpYI2icR8X/3dRrj4GjWMCMWK75HZWjycrfd0nNLdhKyGAw2rlTmgq6Sypm3g80aq3LvGJ+Pnb7s6B2IAzNgOyhT8TKlIILZ3wQlYMrVBaVaMTmRItHWY=
      file_glob: true
      file:
      - src/packages/cassandra-reaper-${TRAVIS_TAG}-release.tar.gz
      - src/packages/reaper-*-1.x86_64.rpm
      - src/packages/reaper_*_amd64.deb
      skip_cleanup: true
      on:
        tags: true
services:
- postgresql
- docker
before_install: "./src/ci/before_install.sh"
install: "./src/ci/install.sh"
before_script: "./src/ci/before_script.sh"
script: "./src/ci/script.sh"
after_failure: "./src/ci/after_failure.sh"
